FROM node:18

# Define a pasta de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos de dependência para otimizar o cache
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do projeto
COPY . .

# Expõe a porta padrão do Vite
EXPOSE 5173

# Comando padrão ao iniciar o container
CMD ["npm", "run", "dev", "--", "--host"]
