# Use uma imagem base com Node.js
FROM node:18-alpine

# Instale o Docker CLI
RUN apk add --no-cache docker-cli

# Configure o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto
COPY . .

# Instale as dependências
RUN npm install

# Exponha a porta para desenvolvimento
EXPOSE 3000

# Comando padrão
CMD ["npm", "run", "dev"]
